### ISSUE TITLE
zip command is required for appending to binary

### ISSUE THREAD

**Issue by tgulacsi** [GeertJohan/go.rice#7] opened 2014-04-28 22:03 UTC
The proposed hack (https://github.com/tgulacsi/csv2pdf/commit/8b9f4289881940fa9b1879f213b1277d046a314e#) for "zip -A" replacement: https://github.com/tgulacsi/go/blob/master/zipA/main.go
Iff acceptable, the inner workings can be refactored into a function/library.

Another solution (not using unsafe) needs to copy archive/zip, and modify as needed.

**Comment by GeertJohan** [comment] 2015-01-07 11:59
This is now issue golang/go#8669
@sanderhahn do you want to proceed to propose this change to go's stdlib? Or should I?

**Comment by sanderhahn** [comment] 2015-01-07 12:16
Hey Geert-Johan, the issue is marked accepted maybe for 1.5, but there are
no changes in the archive/writer.go on master. If you want to re-propose
the issue again: that is okay :-) Best regards, Sander

2015-01-07 12:59 GMT+01:00 Geert-Johan Riemer <notifications@github.com>:

> This is now issue golang/go#8669
> <https://github.com/golang/go/issues/8669>
> @sanderhahn <https://github.com/sanderhahn> do you want to proceed to
> propose this change to go's stdlib? Or should I?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeertJohan/go.rice/issues/7#issuecomment-69012875>.
>



-- 
Sander Hahn
06-14211335
sanderhahn@gmail.com

**Comment by GeertJohan** [comment] 2015-01-07 14:22
Ok I'll submit it.

**Comment by sanderhahn** [comment] 2015-10-18 13:47
Issue has been resolved in Go 1.5: https://github.com/golang/go/issues/8669

Now you can use:
```go
	w := zip.NewWriter(f)
	w.SetOffset(startoffset)
```

Example is in the Zip function in [gozip.go](https://github.com/sanderhahn/gozip/blob/master/gozip.go)

**Closed** 2016-01-04 08:09 UTC
