### ISSUE TITLE
ignore option missing

### ISSUE THREAD

**Issue by hryamzik** [GeertJohan/go.rice#80] opened 2016-03-10 15:16 UTC
Here's how it works with both `go-bindata` and `go-bindata-assetfs`:

```
go-bindata-assetfs -ignore=\.DS_Store
```

**Comment by vjeantet** [comment] 2016-07-15 19:32
+1

**Comment by GeertJohan** [comment] 2018-12-29 18:31
Actually #83 is a duplicate of this issue. But there has been more discussion in that issue so I'm closing this one. This is a good feature request thought, thanks for sending it in!

**Closed by GeertJohan** 2018-12-29 18:31 UTC
